server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/tm_baseball?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: mySqlPool
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 191408478308-f2bab1dvhqj3temdm7ktl8sdtlci4ohh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile